#!/usr/bin/env Rscript

# Publication-style GNINA/Vina comparison figures.
#
# This script reads the audited run-level table generated by
# analyze_gnina_pose_rescoring.py. It does not recompute docking statistics.

suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(patchwork)
  library(readr)
  library(scales)
  library(svglite)
  library(tidyr)
})

args <- commandArgs(trailingOnly = FALSE)
file_arg <- sub("^--file=", "", args[grepl("^--file=", args)])
script_path <- normalizePath(file_arg, mustWork = TRUE)
repo_root <- normalizePath(file.path(dirname(script_path), "..", ".."), mustWork = TRUE)
analysis_dir <- file.path(repo_root, "outputs", "docking_campaign", "analysis", "gnina")
figure_dir <- file.path(repo_root, "outputs", "docking_campaign", "figures", "gnina_comparison")
dir.create(figure_dir, recursive = TRUE, showWarnings = FALSE)

runs <- read_csv(
  file.path(analysis_dir, "run_summary.csv"),
  show_col_types = FALSE,
  progress = FALSE
)

stopifnot(nrow(runs) == 45L)
stopifnot(sum(runs$n_poses) == 738L)

group_order <- c(
  "FYN canonical",
  "BACE1 canonical",
  "BACE1-476",
  "BACE1-457",
  "CHRNA7 canonical",
  "CHRFAM7A at A face",
  "CHRFAM7A at B face"
)

display_names <- c(
  "FYN canonical" = "FYN  |  canonical",
  "BACE1 canonical" = "BACE1  |  canonical",
  "BACE1-476" = "BACE1  |  476-aa model",
  "BACE1-457" = "BACE1  |  457-aa model",
    "CHRNA7 canonical" = "α7  |  canonical",
  "CHRFAM7A at A face" = "CHRFAM7A  |  A-face",
  "CHRFAM7A at B face" = "CHRFAM7A  |  B-face"
)

palette <- c(
  "FYN canonical" = "#416788",
  "BACE1 canonical" = "#264653",
  "BACE1-476" = "#2A9D8F",
  "BACE1-457" = "#E76F51",
  "CHRNA7 canonical" = "#4A5568",
  "CHRFAM7A at A face" = "#7868E6",
  "CHRFAM7A at B face" = "#C44569"
)

ink <- "#18212B"
muted <- "#5D6975"
grid <- "#DCE3E8"
paper <- "#FFFFFF"
pass_fill <- "#E8F4EE"
fail_fill <- "#FCEDEC"
pass_ink <- "#287A55"
fail_ink <- "#B4453D"

theme_presentation <- function(base_size = 13) {
  theme_minimal(base_family = "Noto Sans", base_size = base_size) +
    theme(
      plot.background = element_rect(fill = paper, colour = NA),
      panel.background = element_rect(fill = paper, colour = NA),
      plot.title = element_text(
        family = "Noto Sans", face = "bold", size = rel(1.72),
        colour = ink, hjust = 0, margin = margin(b = 7)
      ),
      plot.subtitle = element_text(
        size = rel(1.00), colour = muted, hjust = 0, lineheight = 1.12,
        margin = margin(b = 20)
      ),
      plot.caption = element_text(
        size = rel(0.72), colour = muted, hjust = 0,
        lineheight = 1.12, margin = margin(t = 16)
      ),
      plot.title.position = "plot",
      plot.caption.position = "plot",
      axis.title = element_text(face = "bold", colour = ink, size = rel(0.90)),
      axis.text = element_text(colour = ink, size = rel(0.84)),
      axis.text.y = element_text(hjust = 1),
      panel.grid.minor = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.major.x = element_line(colour = grid, linewidth = 0.45),
      strip.text = element_text(face = "bold", colour = ink, size = rel(0.92)),
      strip.background = element_blank(),
      legend.position = "top",
      legend.justification = "left",
      legend.title = element_blank(),
      legend.text = element_text(colour = ink, size = rel(0.78)),
      legend.key.width = grid::unit(1.15, "lines"),
      plot.margin = margin(26, 34, 22, 30)
    )
}

mean_ci <- function(x) {
  n <- sum(!is.na(x))
  avg <- mean(x, na.rm = TRUE)
  se <- sd(x, na.rm = TRUE) / sqrt(n)
  tibble(mean = avg, lower = avg - qt(0.975, n - 1) * se, upper = avg + qt(0.975, n - 1) * se)
}

save_plot <- function(plot, filename, width = 14.2, height = 8.0) {
  ggsave(
    file.path(figure_dir, paste0(filename, ".png")), plot,
    device = ragg::agg_png, width = width, height = height,
    units = "in", dpi = 240, background = paper
  )
  ggsave(
    file.path(figure_dir, paste0(filename, ".pdf")), plot,
    device = cairo_pdf, width = width, height = height,
    units = "in", bg = paper
  )
  ggsave(
    file.path(figure_dir, paste0(filename, ".svg")), plot,
    device = svglite::svglite, width = width, height = height,
    units = "in", bg = paper
  )
}

# ---------------------------------------------------------------------------
# Figure 1: effect estimation plus pose displacement
# ---------------------------------------------------------------------------

reference_rows <- runs %>%
  filter(group %in% c("BACE1 canonical", "CHRNA7 canonical")) %>%
  transmute(
    system,
    seed,
    ref_cnn_affinity = vina_rank1_cnn_affinity
  )

effect_rows <- runs %>%
  filter(group %in% c("BACE1-476", "BACE1-457", "CHRFAM7A at A face", "CHRFAM7A at B face")) %>%
  left_join(reference_rows, by = c("system", "seed")) %>%
  mutate(
    delta_affinity = vina_rank1_cnn_affinity - ref_cnn_affinity,
    display = recode(group, !!!display_names),
    display = factor(
      display,
      levels = rev(unname(display_names[c(
        "BACE1-476", "BACE1-457", "CHRFAM7A at A face", "CHRFAM7A at B face"
      )]))
    )
  )

effect_summary <- effect_rows %>%
  group_by(group, display) %>%
  summarise(mean_ci(delta_affinity), .groups = "drop") %>%
  mutate(label = sprintf("%+.2f", mean))

effect_plot <- ggplot(effect_rows, aes(delta_affinity, display, colour = group)) +
  annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = fail_fill, alpha = 0.58) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = pass_fill, alpha = 0.58) +
  geom_vline(xintercept = 0, colour = ink, linewidth = 0.75) +
  geom_point(
    position = position_jitter(height = 0.075, width = 0),
    size = 2.4, alpha = 0.42, stroke = 0
  ) +
  geom_errorbarh(
    data = effect_summary,
    aes(xmin = lower, xmax = upper, y = display),
    height = 0, linewidth = 1.8, colour = ink, inherit.aes = FALSE
  ) +
  geom_point(
    data = effect_summary,
    aes(mean, display), shape = 21, size = 5.2,
    fill = paper, stroke = 1.35, inherit.aes = FALSE
  ) +
  geom_text(
    data = effect_summary,
    aes(mean, display, label = label),
    nudge_y = 0.24, colour = ink, fontface = "bold", size = 3.7,
    inherit.aes = FALSE
  ) +
  scale_colour_manual(values = palette, guide = "none") +
  scale_x_continuous(
    breaks = seq(-3.5, 0.5, 0.5),
    limits = c(-3.72, 0.26),
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    title = "Predicted affinity shift",
    subtitle = "Alternate minus canonical, paired within seed",
    x = "ΔCNNaffinity  (higher is better)",
    y = NULL
  ) +
  theme_presentation(12.5) +
  theme(
    plot.title = element_text(size = 17),
    plot.subtitle = element_text(size = 11.5, margin = margin(b = 12)),
    axis.text.y = element_text(face = "bold"),
    plot.margin = margin(16, 16, 12, 12)
  )

geometry_groups <- c(
  "BACE1 canonical", "BACE1-476", "BACE1-457",
  "CHRNA7 canonical", "CHRFAM7A at A face", "CHRFAM7A at B face"
)

geometry_rows <- runs %>%
  filter(group %in% geometry_groups) %>%
  mutate(
    display = recode(group, !!!display_names),
    display = factor(display, levels = rev(unname(display_names[geometry_groups])))
  )

geometry_summary <- geometry_rows %>%
  group_by(group, display) %>%
  summarise(mean_ci(cnn_selected_rmsd_angstrom), .groups = "drop") %>%
    mutate(label = sprintf("%.1f Å", mean))

geometry_plot <- ggplot(geometry_rows, aes(cnn_selected_rmsd_angstrom, display, colour = group)) +
  annotate("rect", xmin = 0, xmax = 2, ymin = -Inf, ymax = Inf, fill = pass_fill, alpha = 0.72) +
  geom_vline(xintercept = 2, colour = pass_ink, linewidth = 0.8, linetype = "22") +
  geom_point(
    position = position_jitter(height = 0.075, width = 0),
    size = 2.35, alpha = 0.40, stroke = 0
  ) +
  geom_errorbarh(
    data = geometry_summary,
    aes(xmin = lower, xmax = upper, y = display),
    height = 0, linewidth = 1.8, colour = ink, inherit.aes = FALSE
  ) +
  geom_point(
    data = geometry_summary,
    aes(mean, display), shape = 21, size = 5.0,
    fill = paper, stroke = 1.3, inherit.aes = FALSE
  ) +
  scale_colour_manual(values = palette, guide = "none") +
  scale_x_continuous(
    breaks = seq(0, 12, 2), limits = c(0, 12.25),
    expand = expansion(mult = c(0, 0))
  ) +
  labs(
    title = "CNN-selected pose displacement",
    subtitle = "Green zone marks the conventional <2 Å redocking criterion",
    x = "RMSD to canonical crystallographic pose (Å)",
    y = NULL
  ) +
  theme_presentation(12.5) +
  theme(
    plot.title = element_text(size = 17),
    plot.subtitle = element_text(size = 11.5, margin = margin(b = 12)),
    axis.text.y = element_text(face = "bold"),
    plot.margin = margin(16, 12, 12, 16)
  )

matched_comparison <- effect_plot + geometry_plot +
  plot_layout(widths = c(1.04, 1)) +
  plot_annotation(
    title = "GNINA rescoring reinforces the strongest disruption hypotheses",
    subtitle = paste0(
      "BACE1-457 and the CHRFAM7A B-face model show the largest paired score losses and displaced selected poses.\n",
      "Points are seeded Vina ensembles; open circles are means with 95% t intervals."
    ),
    caption = paste0(
      "CNNaffinity is a learned model output, not a Vina kcal/mol value. ",
      "GNINA rescored fixed Vina poses; this is scoring consensus, not independent conformational sampling."
    ),
    theme = theme_presentation(13)
  )

save_plot(matched_comparison, "gnina_matched_comparison", 14.2, 8.0)

# ---------------------------------------------------------------------------
# Figure 2: canonical validation in one restrained paired chart
# ---------------------------------------------------------------------------

canonical_order <- c("FYN canonical", "BACE1 canonical", "CHRNA7 canonical")
canonical_rows <- runs %>%
  filter(group %in% canonical_order) %>%
  group_by(group) %>%
  arrange(seed, .by_group = TRUE) %>%
  mutate(
    row_offset = seq(-0.19, 0.19, length.out = n()),
    group_y = match(group, rev(canonical_order)),
    y = group_y + row_offset
  ) %>%
  ungroup()

canonical_means <- canonical_rows %>%
  group_by(group, group_y) %>%
  summarise(
    vina_mean = mean(vina_top_rmsd_angstrom),
    gnina_mean = mean(cnn_selected_rmsd_angstrom),
    passed = sum(cnn_selected_rmsd_angstrom < 2),
    total = n(),
    .groups = "drop"
  ) %>%
  mutate(status = if_else(passed == total, "preserved", "not preserved"))

validation_plot <- ggplot(canonical_rows) +
  annotate("rect", xmin = 0, xmax = 2, ymin = 0.45, ymax = 3.55, fill = pass_fill) +
  annotate("rect", xmin = 2, xmax = 3.7, ymin = 0.45, ymax = 3.55, fill = fail_fill) +
  geom_vline(xintercept = 2, colour = ink, linewidth = 0.85, linetype = "22") +
  geom_segment(
    aes(x = vina_top_rmsd_angstrom, xend = cnn_selected_rmsd_angstrom, y = y, yend = y),
    colour = "#A6B0BA", linewidth = 1.0, alpha = 0.70
  ) +
  geom_point(
    aes(vina_top_rmsd_angstrom, y),
    shape = 21, size = 3.7, fill = paper, colour = "#6B7682", stroke = 1.15
  ) +
  geom_point(
    aes(cnn_selected_rmsd_angstrom, y, fill = group),
    shape = 23, size = 4.0, colour = paper, stroke = 0.75
  ) +
  geom_segment(
    data = canonical_means,
    aes(x = vina_mean, xend = gnina_mean, y = group_y, yend = group_y),
    colour = ink, linewidth = 2.0, inherit.aes = FALSE
  ) +
  geom_point(
    data = canonical_means,
    aes(vina_mean, group_y),
    shape = 21, size = 5.8, fill = paper, colour = ink, stroke = 1.5,
    inherit.aes = FALSE
  ) +
  geom_point(
    data = canonical_means,
    aes(gnina_mean, group_y, fill = group),
    shape = 23, size = 6.2, colour = ink, stroke = 1.2,
    inherit.aes = FALSE
  ) +
  geom_label(
    data = canonical_means,
    aes(
      x = 3.62, y = group_y,
      label = sprintf("%d/%d <2 Å", passed, total),
      colour = status
    ),
    hjust = 1, fontface = "bold", size = 4.0,
    fill = alpha(paper, 0.88), label.size = 0,
    inherit.aes = FALSE
  ) +
  annotate("text", x = 1.92, y = 3.43, label = "pose-valid", hjust = 1, colour = pass_ink, fontface = "bold", size = 4) +
  annotate("text", x = 2.08, y = 3.43, label = "displaced", hjust = 0, colour = fail_ink, fontface = "bold", size = 4) +
  scale_fill_manual(values = palette, guide = guide_legend(override.aes = list(shape = 23, size = 4.5))) +
  scale_colour_manual(values = c("preserved" = pass_ink, "not preserved" = fail_ink), guide = "none") +
  scale_x_continuous(breaks = seq(0, 3.5, 0.5), limits = c(0, 3.7), expand = expansion(mult = 0)) +
  scale_y_continuous(
    breaks = 1:3,
    labels = rev(c("FYN", "BACE1", "α7")),
    limits = c(0.45, 3.58)
  ) +
  labs(
    title = "CNN reranking preserves BACE1 and α7 binding modes—but not FYN",
    subtitle = paste0(
      "Each thin line is one Vina search. Circles show the Vina rank-1 pose; diamonds show the pose selected by CNNscore.\n",
      "Large symbols mark group means."
    ),
    x = "RMSD to crystallographic ligand (Å)",
    y = NULL,
    caption = paste0(
      "BACE1: GNINA retained Vina rank 1 in 6/6 runs. α7: GNINA selected rank 2, but all poses remained <2 Å. ",
      "FYN is a transparent scoring-method disagreement."
    ),
    fill = NULL
  ) +
  theme_presentation(13.5) +
  theme(
    legend.position = "none",
    axis.text.y = element_text(face = "bold", size = 13),
    panel.grid.major.y = element_line(colour = paper, linewidth = 2.3),
    plot.margin = margin(28, 38, 24, 34)
  )

save_plot(validation_plot, "gnina_pose_selection_validation", 14.2, 7.5)

# ---------------------------------------------------------------------------
# Figure 3: rank-agreement dashboard
# ---------------------------------------------------------------------------

agreement_rows <- runs %>%
  mutate(
    group = factor(group, levels = rev(group_order)),
    display = factor(recode(as.character(group), !!!display_names), levels = rev(unname(display_names[group_order])))
  )

rank_summary <- agreement_rows %>%
  group_by(group, display) %>%
  summarise(
    median = median(cnn_selected_vina_rank),
    lower = quantile(cnn_selected_vina_rank, 0.25),
    upper = quantile(cnn_selected_vina_rank, 0.75),
    agreement = sum(cnn_vina_rank1_agree),
    total = n(),
    .groups = "drop"
  ) %>%
  mutate(agreement_label = sprintf("%d/%d", agreement, total))

rank_plot <- ggplot(agreement_rows, aes(cnn_selected_vina_rank, display, colour = group)) +
  annotate("rect", xmin = 0.5, xmax = 1.5, ymin = -Inf, ymax = Inf, fill = pass_fill) +
  geom_vline(xintercept = 1, colour = pass_ink, linewidth = 0.8) +
  geom_point(
    position = position_jitter(height = 0.075, width = 0.04),
    size = 2.7, alpha = 0.48, stroke = 0
  ) +
  geom_errorbarh(
    data = rank_summary,
    aes(xmin = lower, xmax = upper, y = display),
    height = 0, linewidth = 1.8, colour = ink, inherit.aes = FALSE
  ) +
  geom_point(
    data = rank_summary,
    aes(median, display), shape = 21, fill = paper,
    colour = ink, size = 4.8, stroke = 1.35, inherit.aes = FALSE
  ) +
  geom_text(
    data = rank_summary,
    aes(x = 21.4, y = display, label = agreement_label),
    colour = muted, size = 3.7, fontface = "bold", hjust = 1,
    inherit.aes = FALSE
  ) +
  annotate("text", x = 21.4, y = 7.48, label = "rank-1 agreement", colour = muted, size = 3.4, hjust = 1) +
  scale_colour_manual(values = palette, guide = "none") +
  scale_x_continuous(breaks = c(1, 5, 10, 15, 20), limits = c(0.5, 21.6), expand = expansion(mult = 0)) +
  labs(
    title = "Pose chosen by CNNscore",
    subtitle = "Original rank within each Vina ensemble",
    x = "Original Vina pose rank  (1 = same top pose)",
    y = NULL
  ) +
  theme_presentation(12.3) +
  theme(
    plot.title = element_text(size = 17),
    plot.subtitle = element_text(size = 11.5, margin = margin(b = 12)),
    axis.text.y = element_text(face = "bold", size = 10.2),
    plot.margin = margin(18, 12, 12, 12)
  )

correlation_summary <- agreement_rows %>%
  group_by(group, display) %>%
  summarise(mean_ci(spearman_vina_quality_vs_cnn_score), .groups = "drop")

correlation_plot <- ggplot(agreement_rows, aes(spearman_vina_quality_vs_cnn_score, display, colour = group)) +
  annotate("rect", xmin = -1, xmax = 0, ymin = -Inf, ymax = Inf, fill = fail_fill, alpha = 0.55) +
  annotate("rect", xmin = 0, xmax = 1, ymin = -Inf, ymax = Inf, fill = pass_fill, alpha = 0.55) +
  geom_vline(xintercept = 0, colour = ink, linewidth = 0.75) +
  geom_point(
    position = position_jitter(height = 0.075, width = 0),
    size = 2.7, alpha = 0.46, stroke = 0
  ) +
  geom_errorbarh(
    data = correlation_summary,
    aes(xmin = lower, xmax = upper, y = display),
    height = 0, linewidth = 1.8, colour = ink, inherit.aes = FALSE
  ) +
  geom_point(
    data = correlation_summary,
    aes(mean, display), shape = 21, fill = paper,
    colour = ink, size = 4.8, stroke = 1.35, inherit.aes = FALSE
  ) +
  geom_text(
    data = correlation_summary,
    aes(mean, display, label = sprintf("%.2f", mean)),
    nudge_y = 0.23, colour = ink, fontface = "bold", size = 3.4,
    inherit.aes = FALSE
  ) +
  scale_colour_manual(values = palette, guide = "none") +
  scale_x_continuous(breaks = seq(-1, 1, 0.5), limits = c(-1, 1), expand = expansion(mult = 0)) +
  labs(
    title = "Within-ensemble rank correlation",
    subtitle = "Vina pose quality versus CNNscore",
    x = "Spearman ρ  (positive = similar ordering)",
    y = NULL
  ) +
  theme_presentation(12.3) +
  theme(
    plot.title = element_text(size = 17),
    plot.subtitle = element_text(size = 11.5, margin = margin(b = 12)),
    axis.text.y = element_blank(),
    plot.margin = margin(18, 12, 12, 12)
  )

agreement_plot <- rank_plot + correlation_plot +
  plot_layout(widths = c(1.12, 0.88)) +
  plot_annotation(
    title = "Vina–GNINA agreement is strongly system-dependent",
    subtitle = paste0(
      "BACE1 canonical is the only exact rank-1 consensus case. α7 remains geometrically valid despite rank-2 selection;\n",
      "FYN and modeled alternates show larger ranking divergence."
    ),
    caption = paste0(
      "Open circles show medians (left) or means (right); horizontal bars show IQRs or 95% t intervals. ",
      "Correlation measures ranking similarity, not experimental accuracy."
    ),
    theme = theme_presentation(13)
  )

save_plot(agreement_plot, "vina_gnina_rank_agreement", 14.2, 8.0)

message("Rendered three GNINA comparison figures in: ", figure_dir)
